### ISSUE TITLE
not certified in Home app?

### ISSUE THREAD

**Issue by kaparmar** [grover/homebridge-telegram#17]
Hi, thanks in advance for all the help!

I am having problems getting this to work. It appears in the Home app as 'not certified'. I have received the Error Shutting Down message a couple of times, so I know it is linked to the right Telegram chat, etc. Below is my code:

        {
            "platform": "Telegram",
            "bots": [
                {
                    "name": "Open Rain Bot",
                    "token": "XXXXXX:XXXXXXXXXXxxXX-X",
                    "chat": "-XXXXXXXX",
                    "error": "Something broken. I'm shutting down.",
                    "notifications": {
                        "Raining": {
                            "mode": "HTML",
                            "randomize": false,
                            "messages": [
                                "<b>It's Raining!</b>",
                                "The window in the TV room is open and it's raining."
                            ]
                        }
                    }
                }
            ]
        }

**Comment by reindewaal** [comment]
I’m seeing the same issue. Did you manage to get it working yet?

**Comment by kaparmar** [comment]
@reindewaal no luck =-(

**Comment by Bastie82** [comment]
Homekit can't handle it. You have to use the Eve app, there you can see the individual switches with the messages.

**Comment by moamen121** [comment]
Hi why when I install the Telegram plugin I get a problem with JSON what can be done????

**Comment by moamen121** [comment]
TypeError: Cannot read property 'forEach' of undefined
    at TelegramPlatform.accessories (C:\Program Files\nodejs\node_modules\homebridge-telegram\src\index.js:43:10)
    at C:\Program Files\nodejs\node_modules\homebridge\src\bridgeService.ts:529:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (C:\Program Files\nodejs\node_modules\homebridge\src\bridgeService.ts:523:12)
    at C:\Program Files\nodejs\node_modules\homebridge\src\server.ts:445:42
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (C:\Program Files\nodejs\node_modules\homebridge\src\server.ts:372:27)
    at Server.start (C:\Program Files\nodejs\node_modules\homebridge\src\server.ts:159:29

**Comment by Geek-MD** [comment]
> I’m seeing the same issue. Did you manage to get it working yet?

Create a scene in Eve app which activates the switch created by homebridge-telegram plugin. Once scene is created, you can return to Home app and add that scene to the corresponding automation.
